In [66]:
! pip install numpy

In [67]:
#importing numpy

In [68]:
import numpy

In [69]:
import numpy as np


In [70]:
# syntax-how do you create arrays in numpy
np.array([])
#1D Arrays-vector


array([], dtype=float64)

In [71]:
x=[1,2,3,4,5,6]

In [72]:
np.array([])

array([], dtype=float64)

In [73]:
test1=np.array([4,5,6])

In [74]:
type(test1)

numpy.ndarray

In [75]:
array1=np.array([1,2,3,4,5])

In [76]:
array1

array([1, 2, 3, 4, 5])

In [77]:
#create a 1D array and check the type
array2=np.array([1,2,3,4,5,6,7])

In [78]:
type(array2)

numpy.ndarray

In [79]:
array2.ndim

1

In [80]:
#shape(rows and columns)
array2.shape

(7,)

In [81]:
#getting the size(no of elements)
array2.size

7

# 2D Arrays-Matrix
rows and columns

In [82]:
np.array([[0,1,2,3],[10,11,12,13],[14,15,16,17]])

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [83]:
array2d=np.array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

# Accessing 1D arrays
import numpy as np

In [84]:
array1=np.array([1,2,3,4,5,6,7,8])

In [85]:
#retrieve element
type(array1)

numpy.ndarray

In [86]:
array1[0]

1

In [87]:
array1[-1]

8

# Accessing 2D

In [88]:
array2d=np.array([[2,4,6,8],[10,12,14,15]])
array2d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 15]])

In [89]:
#dimension
array2d.ndim

2

In [90]:
#shape
array2d.shape

(2, 4)

In [91]:
array2d.size

8

In [92]:
#roes,columns access element 6
array2d[1,1]

12

In [93]:
array2d[0,3]

8

# 1D Slicing

In [94]:
oned=np.array([11,21,35,47,59,69,71,18,19,10])

In [95]:
oned

array([11, 21, 35, 47, 59, 69, 71, 18, 19, 10])

In [96]:
#select entire array using slicing
oned[0:10]

array([11, 21, 35, 47, 59, 69, 71, 18, 19, 10])

In [97]:
oned[3:6]

array([47, 59, 69])

In [98]:
oned[-3:]

array([18, 19, 10])

In [99]:
oned[:5]

array([11, 21, 35, 47, 59])

# 2D Slicing
array2d=np.array([[2,4,6,8],[10,12,14,15]])

In [100]:
array2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
array2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [101]:
array2d[1,0:3]

array([6, 7, 8])

In [102]:
#retrieve elements 2 and 7
#retrieve elements in the first row
array2d[0:2,1]


array([2, 7])

In [103]:
array2d[1,:6]

array([ 6,  7,  8,  9, 10])

# Random number generation
x=np.random.randint(1,100)

In [104]:
import numpy as np

In [105]:
#generate random numbers between 1 and 40
np.random.randint(1,40)

33

In [106]:
#generate random numbers between 20 and 42
np.random.randint(20,42)


23

In [107]:
#generate 500 numbers between 1 and 1000000
np.random.randint(1,1000000,size=500)

array([619585, 838357, 743564, 578436, 712511, 721798, 491803, 899095,
       435900, 224795, 790940, 175758, 181488, 689096, 397715, 739999,
       643995, 821372,  55586, 473788, 872270, 878506, 135832, 808221,
       905380, 285097, 344508, 516588, 940116, 105214, 663426, 436406,
       256722, 415195, 751921, 123632, 532746, 716283, 843754, 861489,
       708566, 259411, 951626, 483952, 884178, 278917, 315237, 866874,
        89916, 673214,  44465, 233492, 273493, 750394, 408120, 298765,
       596930, 745284, 385677, 833236, 946500, 982673, 213007, 396221,
       704974, 129625, 356882, 369461, 500557, 727324, 913165, 469508,
       721019, 321074, 504167, 518687, 248679, 416074, 917208, 969882,
       850784, 287162, 126591, 660864, 783150, 852722, 445403, 717362,
       686912, 552200, 209306, 495880, 391702, 574870, 120105, 257203,
       926372,  62834, 694043, 789496, 845826, 253964, 278985, 429374,
       766882, 336338, 877768, 951486,  89642, 581275, 976134, 753419,
      

# Arange

In [108]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
np.arange(1001)

array([   0,    1,    2, ...,  998,  999, 1000])

In [110]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Reshaping

In [111]:
#create a one dimensional array
arr=np.array([1,2,3,4,5,6,7,8,9,10])

#Reshape the array into a two-dimensional array with 2 rows and 5 columns
reshaped_arr=arr.reshape((2,5))

print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [112]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
x.shape


(2, 3)

In [114]:
x.size

6

In [115]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
even=np.array([2,4,6,8,10,12])
even.size
even.shape

(6,)

In [117]:
even.reshape(2,3)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [118]:
even.shape

(6,)

# search array

In [119]:
dataset=np.arange(20,31)

In [120]:
dataset

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [121]:
np.where(dataset==24)#output index

(array([4], dtype=int64),)

In [122]:
dataset[np.where(dataset>23)]

array([24, 25, 26, 27, 28, 29, 30])

# other examples


In [123]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
merged=np.where(arr1>3,arr1,arr2)
merged

array([10, 20, 30,  4,  5])

# computation with arrays

In [124]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
a.mean()

3.5

In [126]:
a.min()

1

In [127]:
a.max()

6

In [128]:
a.sum()

21

In [129]:
#supplying the keyword axis to your sum(rows)
#axis=0 [rows]
a.sum(axis=0)

array([5, 7, 9])

In [131]:
a.sum(axis=1)#[columns]

array([ 6, 15])

# Merge/Join arrays

In [144]:
array1=np.arange(0,9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [146]:
array2=np.arange(10,19).reshape(3,3)
array2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
#merge along the rows

In [147]:
np.concatenate((array1,array2),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
#merge along the columns(concatenate)

In [148]:
np.concatenate((array1,array2),axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])